spring:
  application:
    name: project-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project-service?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Pradeep@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
 port: 8082
 error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false

UserWSServiceBaseURL: http://localhost:8080/api/users